name: farming_trial
main: com.crunchiest.Plugin
version: 0.1.6
api-version: 1.18

permissions:
  farmtrial.toggletrampling:
    default: false

commands:
  toggle_trampling:
    description: allows moderators to toggle trampling for player.
    usage: /<command>