name: farming_trial
main: com.crunchiest.FarmingTrial
version: 0.2.0
api-version: 1.18

permissions:
  farmtrial.toggletrampling:
    default: false

commands:
  toggle_trampling:
    description: allows moderators to toggle trampling for player.
    usage: /<command>