name: FarmingTrial
main: com.crunchiest.FarmingTrial
version: 0.3.2
api-version: 1.18

commands:
  toggle_trampling:
    description: allows moderators to toggle trampling for player.
    usage: /<command>
    permission: farmtrial.toggletrampling
    default: false
    permission-message: you don't have permission to do that.

  give_potion:
    description: Gives custom Registered Potion to given player.
    usage: /<command>
    permission: farmtrial.givepotion
    default: false
    permission-message: you don't have permission to do that.

  farmtrial:
    description: reload plugin /farmtrial reload.
    usage: /<command>
    permission: farmtrial.reload
    default: false
    permission-message: you don't have permission to do that.

